server:
  port: 9090
  servlet:
    context-path: /hyy

spring:
  profiles:
    active: test

  thymeleaf:
    servlet:
      content-type: text/html
    suffix: .html
    mode: HTML5
    encoding: UTF-8

  datasource:
    url: jdbc:mysql://localhost:3306/springboot_demo?characterEncoding=utf8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

name: hyy